name: Build and Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [main]
permissions:
  contents: write

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # harus cocok dengan Gemfile

      - name: Install Dependencies
        run: |
          gem install bundler -v 2.6.9
          bundle _2.6.9_ install --jobs 4 --retry 3

      - name: Build site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
